import = [
	"~/.config/alacritty/gruvbox_material_medium_dark.toml"
	]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
dynamic_padding = false
padding = { x = 5, y = 5 }

[font]
size = 9

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"
